// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import styles from "./page.module.css";
import { poppins, rethink } from "@/app/lib/fonts";
import Home from "./page";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={`${poppins.variable} ${rethink.variable}`}>
      <body className="antialiased body">
        {children}
      </body>
    </html>
  );
}
